version: '3.4'

services:

  nginx:
    # https://hub.docker.com/_/nginx/
    image: nginx:1.15.0
    hostname: nginx
    ports:
      # HTTP TCP 80
      - mode: host
        target: 80
        published: 80
        protocol: tcp
      # HTTPS TCP 443
      - mode: host
        target: 443
        published: 443
        protocol: tcp
    networks:
      - nginx-net1
    volumes:
      - type: bind
        source: /opt/nginx/conf.d/
        target: /etc/nginx/conf.d/
      - type: bind
        source: /opt/nginx/letsencrypt
        target: /etc/nginx/letsencrypt
      - type: bind
        source: /opt/nginx/ssl
        target: /etc/nginx/ssl

networks:
  nginx-net1:

